#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 /app/manage.py migrate --no-input
#python3 /app/manage.py collectstatic --no-input

python3 /app/manage.py createsuperuser --username admin  --password changemesoon123 --noinput  --email 'changeme@email.com'
#python3 /app/manage.py runserver 0.0.0.0:8000

app/gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000