# Generated by Django 4.0.5 on 2022-07-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_technologies_project_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='service type')),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(related_name='services', to='api.technology', verbose_name='technologies')),
            ],
            options={
                'verbose_name_plural': 'services',
                'ordering': ('updated_at',),
            },
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
