# Generated by Django 4.0.5 on 2022-07-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_delete_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.TextField(default='test.com', max_length=300),
            preserve_default=False,
        ),
    ]
