# Generated by Django 4.0.5 on 2022-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_image_url_service_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetTheTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='FullName')),
                ('description', models.TextField(max_length=1000, verbose_name='About Me')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MeetTheTeam',
                'ordering': ('updated_at',),
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='technology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
