# Generated by Django 4.1.1 on 2022-09-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_meettheteam_alter_project_image_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meettheteam",
            options={
                "ordering": ("updated_at", "name"),
                "verbose_name_plural": "MeetTheTeam",
            },
        ),
    ]
