name: "Deploy Packer AMI"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true 
        options:
          - production
        type: choice 

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}


jobs: 
  deploy-django:
    name: "Build AMI"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash 

    steps:
     # checkout the repo to Github Actions runner
    - name: Checkout 
      uses: actions/checkout@v2 
 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETKEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Create Packer Image
      id: create-image
      env:
        PKR_VAR_aws-profile: ${{ secrets.AWS_PROFILE }}
        PKR_VAR_aws-region: ${{ secrets.AWS_REGION }}
        PKR_VAR_aws-secretkey: ${{ secrets.AWS_SECRETKEY }}
        PKR_VAR_aws-accesskey: ${{ secrets.AWS_ACCESSKEY }}
        PKR_VAR_secret-name: ${{ secrets.PORTFOLIO_DB_SECRET }}
      run: |
        cd Terraform
        cd packer
        packer validate docker-image.pkr.hcl
        packer build docker-image.pkr.hcl 