name: "Deploy Email Lambda"

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true 
        options:
          - production
        type: choice 

env:
  aws-region: ${{ secrets.AWS_REGION }}
  aws-secret-key: ${{ secrets.AWS_SECRET }}
  aws-access-key: ${{ secrets.AWS_ACCESS }}

jobs:
  deploy-lambda:
    name: "Lambda"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
  
    defaults:
      run:
        shell: bash 
    
    steps:
    # checkout the repo to Github Actions runner
    - name: Checkout 
      uses: actions/checkout@v2 

    # install CDK CLI 
    - name: CDK diff 
      uses: youyo/aws-cdk-github-actions@v2
      with:
          cdk_subcommand: 'diff'
          actions_comment: true
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: 'stack1'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

   