name: "Destroy Database Secrets"

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true 
        options:
          - production
        type: choice 

env:
  TF_WORKSPACE: ${{ github.event.inputs.environment }}
  TF_VAR_aws-region: ${{ secrets.AWS_REGION }}
  TF_VAR_aws-secretkey: ${{ secrets.AWS_SECRETKEY }}
  TF_VAR_aws-accesskey: ${{ secrets.AWS_ACCESSKEY }}
  TF_VAR_secret-name: ${{ secrets.PORTFOLIO_DB_SECRET }}
  TF_VAR_key-name: ${{ secrets.SSH_KEY_NAME }}
  TF_VAR_db-name: ${{ secrets.DATABASE_NAME }} 
  TF_VAR_db-host: ${{ secrets.DATABASE_HOST }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
  
    defaults:
      run:
        shell: bash 
    
    steps:
    # checkout the repo to Github Actions runner
    - name: Checkout 
      uses: actions/checkout@v2 

    # install terraform CLI 
    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRETKEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      id: init
      run: | 
        cd Terraform
        cd secretmanager
        terraform init -backend-config="bucket=portfolio-website-magnolia-bucket" -backend-config="key=terraformstate/portfoliosecrets/terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="access_key=${{  secrets.AWS_ACCESSKEY }}" -backend-config="secret_key=${{ secrets.AWS_SECRETKEY }}"

    - name: Terraform Destroy
      id: validate
      run: |
        cd Terraform
        cd secretmanager 
        terraform destroy --auto-approve